AWSTemplateFormatVersion: '2010-09-09'
Description: AWS EC2 instance creation

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0 
      Tags:
        - Key: stage
          Value: production



